kind: pipeline
name: default

environment:
  GO111MODULE: auto

steps:
  - name: "fetch git tags"
    image: alpine/git
    commands:
      - git fetch --tags

  - name: "build + test"
    image: golang:1.20
    volumes:
      - name: deps
        path: /go
    commands:
      - make
      - cd frontend && go test -v; cd ..
      - cd proxy && go test -v; cd ..

  - name: "run GoReleaser"
    image: golang:1.20
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

volumes:
  - name: deps
    temp: {}

trigger:
  ref:
    include:
    - refs/heads/**
    - refs/tags/0.*
