project_name: bird-lg-go

builds:
  - main: ./frontend
    id: "frontend"
    binary: frontend
    goos: &goos
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    env: &env
      # Go 1.16 and later require SSE, so the default GO386=387 in goreleaser is not supported
      - GO386=softfloat
      - GO111MODULE=auto

  - main: ./proxy
    id: "proxy"
    binary: proxy
    goos: *goos
    env: *env

blobs:
  -
    provider: s3
    endpoint: https://s3.us-west-000.backblazeb2.com
    region: us-west-000
    bucket: highdefnet-bin

    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "{{ .ProjectName }}/{{ .Tag }}"

checksum:
  name_template: 'checksums.txt'
