project_name: bird-lg-go

env:
  - GO111MODULE=on

builds:
  - main: ./frontend
    id: "frontend"
    binary: frontend
    goos: &goos
      - linux

  - main: ./proxy
    id: "proxy"
    binary: proxy
    goos: *goos

blobs:
  -
    provider: s3
    # PUBLIC ACCESS: use https://dl.highdef.network/bird-lg-go/<version>/<filename> or GitHub releases
    endpoint: https://s3.us-west-000.backblazeb2.com
    region: us-west-000
    bucket: highdefnet-bin

    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "{{ .ProjectName }}/{{ .Tag }}"

checksum:
  name_template: 'checksums.txt'
